### ISSUE TITLE
Unrooted Phylogenetic tree with uniformly scaled Genetic Distance

### ISSUE THREAD

**Issue by GeorgeS2019** [nextstrain/ncov-clades-schema#16]
https://erictopol.substack.com/p/a-new-variant-alert
![image](https://user-images.githubusercontent.com/49812372/234995439-81200872-a823-4ce2-a350-ca17faec047d.png)

**Comment by emmahodcroft** [comment]
Hi @GeorgeS2019 , thanks for reaching out. I'm not sure what the issue is that you're reporting here, I'm afraid. This screenshot is actually from another phylogenetic tree of SARS-CoV-2 (from the paper cited, presumably), not the clades scheme of this repo.

Can you clarify the issue please?

**Comment by GeorgeS2019** [comment]
I need regular updates to see the genetic distance of the new XBB variants. 
I need to see the **average change** in the **genetic distance** between XBB and BQ

I need to see if the **speed** of "Genetic Distance" change is **accelerating** in the case of new XBB subvariant

The diagram below shows the "ORDERLY" hierarchical relationship. What I need is the missing **Genetic Distance display in SCALE**

![image](https://user-images.githubusercontent.com/49812372/235089818-b9ea50c2-d795-4fd6-8fa3-04c390241b49.png)

**Comment by GeorgeS2019** [comment]
@emmahodcroft 

source: https://tinyurl.com/y3h3vv55
![image](https://user-images.githubusercontent.com/49812372/235091435-090393f1-4dbb-4d63-a019-ec578dee5258.png)

**Comment by GeorgeS2019** [comment]
@emmahodcroft 

Is there a tool where I could track the spike mutation 478 in e.g. real-time from all submitted sequences?

**Comment by emmahodcroft** [comment]
Hi @GeorgeS2019,

This repo is just to create the schema, as you note, which is just a visual representation, not a true phylogenetic tree. It's beyond the scope of this particular repository to look at more detailed differences between clades.

However Nextstrain also maintains other resources that generate true phylogenetic trees. Note that on most trees you can use the left-hand menu to toggle "Branch length" between Time and Divergence - Divergence will show you the branches in mutations. You can also hover over branches to see more information about them. You can also download the tree files to inspect them in more detail or examine them computationally.

We have recently added XBB.1.16 as 23B and you can track it on any build by looking for that name.

You can look at the latest builds of SARS-CoV-2 phylogenies (focused on the last 6 months) at
https://nextstrain.org/ncov/gisaid/global/6m
https://nextstrain.org/ncov/open/global/6m

You can also find an Omicron-focused build:
https://nextstrain.org/ncov/gisaid/21L/global/6m

We also make 'reference' trees that focus on including representatives of variants/clades to show diversity rather than geographical representation:
https://nextstrain.org/ncov/gisaid/reference
https://nextstrain.org/ncov/open/reference

Finally, for variation in mutation rate you may find Richard Neher's recent papers of interest: 
https://academic.oup.com/ve/article/8/2/veac113/6887176
https://www.biorxiv.org/content/10.1101/2023.01.30.526314v1

There are also many other tools out there where you can track mutations and variants. In particular you can register and use the GISAID site which will allow you to filter by a mutations' presence in all sequences.
Another fantastic site is CoV-Spectrum where one can track a specific mutation through time and geographically.
For S:T478R (in XBB.1.16):
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3AT478R&

For XBB.1.16 itself:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=xbb.1.16*&

I hope all of this helps!

**Comment by GeorgeS2019** [comment]
@emmahodcroft 
Big thank..I am trying to evaluate how likely 478R of XBB.1.16 could unprecedented trigger long covid leading to **loss of vision disability**
